2309

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -45,18 +45,27 @@ jobs:
           name: Load Data
           command: python etl.py load_data
 
+
       - run:
-          name: List files before upload
-          command: |
-            echo "Current directory:"
-            pwd
-            echo "Listing files recursively:"
-            ls -R
+          name: Debug file location
+          command: ls -R
+
+      - run:
+          name: Ensure file exists
+          command: test -f data/crypto.md || (echo "Missing crypto.md!" && exit 1)
 
       - persist_to_workspace:
+          root: .
           paths:
-            - "."
-          root: "~"
+            - data/crypto.md
+
+      - attach_workspace:
+          at: .
+
+      - run:
+          name: List files after workspace
+          command: ls -R
+
       - persist_to_workspace:
           root: .
           paths:
